# Generated by Django 4.1.7 on 2023-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_order_menuitem_url_name_alter_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_is_named',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
